# Dependencies
markdown:         redcarpet
highlighter:      rb-pygments
gems: 
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            scale-meetups
tagline:          ''
description:      'A humble attempt to help humanity scale their meetups. 
                  Made by <a href="https://twitter.com/balki" target="_blank">@balki</a>.'
baseurl:          /

author:
  name:           'Balki'
  url:            https://twitter.com/balki

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
