# Dependencies
markdown:         redcarpet
highlighter:      rb-pygments
gems: 
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            scale-meetups
tagline:          ''
description:      'helping humanity scale meetups.'
baseurl:          /

author:
  name:           'Balki'
  url:            https://twitter.com/balki

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
